---
- name: Install a list of packages
  apt:
    pkg: nginx
    state: present

- name: create index.php
  copy: 
      content: <?php phpinfo();?>
      dest: /var/www/html/index.php
      owner: root
      group: root
      mode: 0644

- name: Copy file default for nginx
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Start and enable service nginx
  service:
    name: nginx
    state: started
    enabled: yes
