---
- name: Install a list of packages
  yum: pkg={{ item }} state=present
  loop:
    - epel-release
    - yum-utils
    - nginx

- name: Start and enable service nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Remote RPM install remi-release.rpm
  yum: 
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: Enable remi-php74 repo
  shell: yum-config-manager --enable remi-php74

- name: Install a list of php-fpm 
  yum: 
    pkg: "{{ item }}" 
    state: present
    update_cache: yes
  loop:
    - php-fpm
    - php-cli

- name: Start and enable service php-fpm
  service:
    name: php-fpm
    state: started
    enabled: yes

- name: Copy file www.conf
  copy:
    src: www.conf
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: '0644'

- name: Create special DocumentRoot for nginx
  file:
    path=/opt/nginx/ansible
    mode=0755
    owner=nginx
    group=nginx
    state=directory

- name: Create index.php
  shell: echo "<?php phpinfo();?>" > /opt/nginx/ansible/index.php
    
- name: Copy file php-fpm.conf
  copy:
    src: php-fpm.conf
    dest: /etc/nginx/conf.d/php-fpm.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart php-fpm

- name: Copy file default.conf for nginx
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx 
