---
- name: Install a list of packages
  yum: pkg={{ item }} state=present
  loop:
    - epel-release
    - yum-utils

- name: Remote RPM install remi-release.rpm
  yum: 
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: Enable remi-php74 repo
  shell: yum-config-manager --enable remi-php74

- name: Install a list of php-fpm 
  yum: 
    pkg: "{{ item }}" 
    state: present
    update_cache: yes
  loop:
    - php
    - php-fpm

- name: Start and enable service php-fpm
  service:
    name: php-fpm
    state: started
    enabled: yes

- name: create index.php
  copy: 
      content: <?php phpinfo();?>
      dest: /var/www/html/index.php
      owner: root
      group: root
      mode: 0644

- name: Copy file www.conf
  copy:
    src: www.conf
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart php-fpm

